name: meedu_demo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter:
    path: ./packages/flutter-tflite
  signature: ^5.5.0
  get: ^4.6.6
  image_picker: ^1.1.2
dependency_overrides:
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/model_crnn-word.h5
    - assets/models/2.tflite
    - assets/models/model.tflite
    - assets/models/fashion_mnist_model.tflite
    - assets/models/text_classification_model.tflite
    - assets/models/face_aging_model.tflite
